name: markers_env
channels:
  - conda-forge
  - defaults
  - gurobi
dependencies:
  - python=3.11
  - numpy
  - pandas
  - scipy
  - matplotlib
  - seaborn
  - scikit-learn
  - pip
  - graphviz
  - python-graphviz
  - ete3
  - lxml  # required by ete3
  - gurobi=11.0.2
  - pyyaml